---
title: "Final Project"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(broom)
library(infer)

arrests <- read.csv("arrests.csv")

dim(arrests)

NFLarrests <- arrests%>%
  mutate(
   margin_of_vic = home_score - away_score
  )
#create new variables that quantifies how close a game was. This is in hopes to see some sort of relationship between more exciting games and more arrests.

ggplot(NFLarrests, aes(y = arrests, x = margin_of_vic, color = margin_of_vic>0)) +
    geom_point(alpha = 0.5)
#This plots the arrests against the margin of victory. It also distinguishes between colors such that home teams lost where the dots are red and won when dots are blue. Based of the plot, there seems to be a correlation between arrests and how close the game was as the data points increase towards 0. In addition, the variability of number of arrests seems to increase the closer you get to zero. Further investigation of both the mean and variability at different margin of victories should be done to see if there is a correlation. 

ggplot(NFLarrests, aes(y = arrests, x = season)) +
    geom_point(alpha = 0.5)
#The number of arrests over time remain relatively constant. This could suggest that stadiums are not doing enough to reduce activity in stadiums.

ggplot(NFLarrests, aes(y = arrests, x = home_team)) +
    geom_point(alpha = 0.5) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
#This plots the home team versus the number of arrests made. There does appear to be a few stadiums that average more arrests than the others. Of these include both New York stadiums, Oakland, Pittsburgh and San Diego.

ggplot(NFLarrests, aes(y = arrests, x = away_team)) +
    geom_point(alpha = 0.5) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
#The away team was also compared to the number of arrests in order to show that the correlation made between arrests and home team was not random. Because the away team appears to be irrelevant to the number of arrests, we can start to conclude that the number of arrests can partly depend on what stadium we are in.

ggplot(NFLarrests, aes(y = arrests, x = margin_of_vic, color = home_team)) +
    geom_point(alpha = 0.5)
#This compares the margin of victory with the home team and then we do the away team below.
 
ggplot(NFLarrests, aes(y = arrests, x = margin_of_vic, color = away_team)) +
    geom_point(alpha = 0.5)
#To further visualize the previous suggestions, we compared the margin of victory to arrests while color coordinating teams. While no pattern seemed to emerge for the away teams, the home teams tended to have certain clusters of colors focused at the top.

ggplot(NFLarrests, aes(y = arrests, x = week_num, color = home_team)) + 
    geom_point(alpha = 0.5)
#Compare the number of arrests to the week number, with colors for the home team.

ggplot(NFLarrests, aes(y = arrests, x = day_of_week, color = home_team)) + 
    geom_point(alpha = 0.5)
#Plot the day of the week against the arrests with different colors for the home team

ggplot(NFLarrests, aes(y = arrests, x = gametime_local, color = home_team)) + 
    geom_point(alpha = 0.5)
#Plots the arrests for each of the local game times, differentiated by home team.

ggplot(NFLarrests, aes(x = arrests, fill = division_game)) + 
    geom_histogram()  + 
    facet_wrap( ~ division_game)
#plots the arrests vs wether or not it is a division game.

ggplot(NFLarrests, aes(x = arrests, fill = home_team)) + 
    geom_histogram()  + 
    facet_wrap( ~ day_of_week)
#plots the arrests for a home team based on the day of the week

NFLarrests <- NFLarrests %>%
  mutate(margin_of_vic = abs(margin_of_vic))

#Looking at the home_team vs. arrests chart, the NY Giants, NY Jets, Oakland (now Las Vegas) Raiders, and Pittsburgh Steelers all have floor numbers of arrests that are greater than zero, so we are going to isolate each team's home game data to see their individual margin of victory versus arrest relationships.

OakArrests <- NFLarrests %>%
  filter(home_team == "Oakland")

ggplot(OakArrests, aes(y = arrests, x = margin_of_vic)) +
    geom_point(alpha = 0.5)
model_oak <- lm(arrests ~ margin_of_vic, data = OakArrests)
summary(model_oak)
confint(model_oak)

PitArrests <- NFLarrests %>%
  filter(home_team == "Pittsburgh")

ggplot(PitArrests, aes(y = arrests, x = margin_of_vic)) +
    geom_point(alpha = 0.5)

NYGiants_arrests <- NFLarrests %>%
  filter(home_team == "New York Giants")
head(NYGiants_arrests)

ggplot(NYGiants_arrests, aes(y = arrests, x = margin_of_vic)) +
    geom_point(alpha = 0.5)
#Created a visualization of this team's margin_of_vic versus arrest relationship, which will be used while creating a linear regression

Giants_model <- lm(arrests ~ margin_of_vic, data = NYGiants_arrests)
summary(Giants_model)

confint(Giants_model)
#The 95% confidence interval for the slope of the relationship between the margin_of_victory and number of arrests at NY Giants home games is [-0.7601545, -0.04792955]. This indicates that though we do not know the true correlation coefficient between these two variables, we are 95% confident that the true value lies between -0.7601545 and -0.04792955. 

ggplot(NYGiants_arrests, aes(x = margin_of_vic, y = arrests)) + 
    geom_point() +
    geom_abline(slope = -0.4040, intercept = 26.6669, color = "red")
#This provides a linear regression model that demonstrates the relationship between the margin of victory and the number of arrests at NY Giants home games. 

NYJets_arrests <- NFLarrests %>%
  filter(home_team == "New York Jets")
head(NYJets_arrests)

ggplot(NYJets_arrests, aes(y = arrests, x = margin_of_vic)) +
    geom_point(alpha = 0.5)
#Created a visualization of this team's margin_of_vic versus arrest relationship, which will be used while creating a linear regression

Jets_model <- lm(arrests ~ margin_of_vic, data = NYJets_arrests)
summary(Jets_model)

confint(Jets_model)
#The 95% confidence interval for the slope of the relationship between the margin_of_victory and number of arrests at NY Jets home games is [-0.2611174, 0.3649023]. This indicates that though we do not know the true correlation coefficient between these two variables, we are 95% confident that the true value lies between these two values. 

ggplot(NYGiants_arrests, aes(x = margin_of_vic, y = arrests)) + 
    geom_point() +
    geom_abline(slope = 0.05189, intercept = 20.79486, color = "red")
```